<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarrosSeeder extends Seeder
{
   /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('carros')->truncate();
        
        DB::table('carros')->insert([
            // Carro 1: Polo
            [
                'id' => 1,
                'modelo' => 'Polo',
                'marca' => 'Volkswagem',
                'ano' => 2024,
                'cor' => 'chumbo',
                'preco' => 80000.00,
                'imagem_capa' => 'https://storage.googleapis.com/dealersites-content/dealersites/vehicles/versions/volkswagen/foto890_44417.webp',
                'imagem_url' => 'https://quatrorodas.abril.com.br/wp-content/uploads/2023/03/Volkswagen-Polo-Track-2023-1.jpg?quality=70&strip=info&w=918&w=636',
                'imagem_url2' => 'https://quatrorodas.abril.com.br/wp-content/uploads/2023/03/Volkswagen-Polo-Track-2023-14.jpeg?quality=70&strip=info&w=920&w=636',
                'imagem_url3' => 'https://quatrorodas.abril.com.br/wp-content/uploads/2023/03/Volkswagen-Polo-Track-2023-2.jpeg?quality=70&strip=info&w=920&w=636',
                'carroceria' => 'Hatch',
                'quilometragem' => 100000,
                'combustivel' => '50',
                'motor' => '1.0',
                'cambio' => 'Manual',
                'descricao' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets',
                'created_at' => '2025-11-11 03:14:04',
                'updated_at' => '2025-11-11 03:14:04',
            ],
            // Carro 2: Onix
            [
                'id' => 2,
                'modelo' => 'Onix',
                'marca' => 'Chevrolet',
                'ano' => 2023,
                'cor' => 'vermelho',
                'preco' => 75000.00,
                'imagem_capa' => 'https://www.santaclarachevrolet.com.br/content/dam/chevrolet/sa/br/pt/master/home/cars/onix/onix-2026/colorizer/onix-rs/onix-rs-2026-cor-branco-summit.jpg?imwidth=1200',
                'imagem_url' => 'https://http2.mlstatic.com/D_NQ_NP_618908-MLA89447014047_082025-OO.webp',
                'imagem_url2' => 'https://s2-autoesporte.glbimg.com/33FhgMMfnkSheLKrKiRBG5VXOuk=/0x0:1400x788/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2022/F/a/WwHytgTPuoIjf4BV9dVA/chevrolet-onix-lt-2023-3.jpg',
                'imagem_url3' => 'https://seminovos.localiza.com.br/model/onix/gallery_onix_1.webp',
                'carroceria' => 'Hatch',
                'quilometragem' => 45220,
                'combustivel' => '45',
                'motor' => '1.0 LTZ',
                'cambio' => 'Automático',
                'descricao' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets',
                'created_at' => '2025-11-11 02:25:20',
                'updated_at' => '2025-11-11 02:25:20',
            ],
            // Carro 3: HB20
            [
                'id' => 3,
                'modelo' => 'HB20',
                'marca' => 'Hyundai',
                'ano' => 2024,
                'cor' => 'branco',
                'preco' => 78000.00,
                'imagem_capa' => 'https://cdn.autopapo.com.br/carro/hyundai/hb20-sport-10-turbo-aut-2020/destaque.png',
                'imagem_url' => 'https://s2-autoesporte.glbimg.com/7HTwImwYvnTEsTdRnVK-D8bkc8U=/0x0:620x413/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2020/Y/Z/Jpb9NtSzmLccBrAgIz6g/2020-02-04-hb20-sport-03-t01pdk3.jpg',
                'imagem_url2' => 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiG1GgKO3gimpFQUx_bvmATS-K05hQ07gdFmJM1YuUNF39UQVoaAdSMRmWzQ_pKddVFnQctfIDvuTpfmmLrLyE5k1unS1fTeUUMdZ_VQqK5fik9R65YpRN65Z4W3sL7Inw3gi6x0GCEYZqzNh5ErxQZyxJNvPcPfBJiCw1z1PhK1PHJM-juLNhyVf-Yfw/s600-rw',
                'imagem_url3' => 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj7BGUIKBxvbhctyilcOKOXtqw-N1EO6FBIYVevpw-u0yQNuD6Ah5DTInVRzSO7yBjEzevDIXvtdsMifl2QpTQEOLcwlacmDPfVZR-mWRbzRfDjf_bX3TOPimiHyrOFno12G1oAkENF5z3kgt_UeyhqjFaufoGrQ/s600-rw',
                'carroceria' => 'Hatch',
                'quilometragem' => 35500,
                'combustivel' => '48',
                'motor' => '1.0 Turbo',
                'cambio' => 'Automático',
                'descricao' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets',
                'created_at' => '2025-11-11 02:26:16',
                'updated_at' => '2025-11-11 02:26:16',
            ],
            // Carro 4: Argo
            [
                'id' => 4,
                'modelo' => 'Argo',
                'marca' => 'Fiat',
                'ano' => 2022,
                'cor' => 'prata',
                'preco' => 72000.00,
                'imagem_capa' => 'https://production.autoforce.com/uploads/version/profile_image/8886/comprar-drive-1-3-automatico_74ef3ee19b.png',
                'imagem_url' => 'https://s2-autoesporte.glbimg.com/OH9xWBhFh6Ejp1IUUp0sknjXW4g=/0x0:5479x3652/1008x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2018/3/r/6qTeMpTGqEvyp2umw2FA/imagem-1-.jpg',
                'imagem_url2' => 'https://seminovos.unidas.com.br/blog/content/uploads/2020/07/Interior-Fiat-Argo-Drive-2019.png',
                'imagem_url3' => 'https://s2-autoesporte.glbimg.com/GJAQ9dXcUW5mZTdONb-o26hN8sk=/0x0:620x413/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2020/L/i/F4Or8ZRzmNmihAoRAa4w/2019-04-26-imagem-3.jpg',
                'carroceria' => 'Hatch',
                'quilometragem' => 75000,
                'combustivel' => '45',
                'motor' => '1.0',
                'cambio' => 'Manual',
                'descricao' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets',
                'created_at' => '2025-11-11 02:29:09',
                'updated_at' => '2025-11-11 02:29:09',
            ],
            // Carro 6: Cronos
            [
                'id' => 6,
                'modelo' => 'Cronos',
                'marca' => 'Fiat',
                'ano' => 2024,
                'cor' => 'prata',
                'preco' => 85000.00,
                'imagem_capa' => 'https://production.autoforce.com/uploads/version/profile_image/11159/comprar-precision-1-3-at_87cdf0543b.png',
                'imagem_url' => 'https://s2-autoesporte.glbimg.com/FdKvjKJRJqgf1MyNSf1N0QFOpvk=/0x0:1920x1280/888x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2025/v/V/84WQB3Tqukyt0CJW58Mw/jml-089.jpg',
                'imagem_url2' => 'https://p2.trrsf.com/image/fget/cf/1548/0/images.terra.com/2024/09/11/fiatcronosdrive1-3my24_055-1iyq0bkunes6t.jpg',
                'imagem_url3' => 'https://s2-autoesporte.glbimg.com/Ub5vKsQTLqE_JSTAhXplOIfG8MM=/0x0:1920x1280/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2025/w/1/7DdOD0Qlu7ljQAaOZmIA/jml-085.jpg',
                'carroceria' => 'Sedan',
                'quilometragem' => 30000,
                'combustivel' => '45',
                'motor' => '1.8',
                'cambio' => 'Manual',
                'descricao' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets',
                'created_at' => '2025-11-11 02:30:17',
                'updated_at' => '2025-11-11 02:30:17',
            ],
            // Carro 7: Versa
            [
                'id' => 7,
                'modelo' => 'Versa',
                'marca' => 'Nissan',
                'ano' => 2023,
                'cor' => 'Vemelho',
                'preco' => 92000.00,
                'imagem_capa' => 'https://www.webmotors.com.br/tabela-fipe/_next/image?url=https%3A%2F%2Fwww.webmotors.com.br%2Fimagens%2Fprod%2F379675%2FNISSAN_VERSA_1.6_16V_FLEX_SR_XTRONIC_37967514081589090.webp&w=1265&q=75',
                'imagem_url' => 'https://cdn.motor1.com/images/mgl/g44go7/s3/nissan-versa-2022.webp',
                'imagem_url2' => 'https://www.autossegredos.com.br/wp-content/webp-express/webp-images/uploads/2020/10/nissan-versa-exclusive-35.jpg.webp',
                'imagem_url3' => 'https://www.autossegredos.com.br/wp-content/webp-express/webp-images/uploads/2020/10/nissan-versa-exclusive-19.jpg.webp',
                'carroceria' => 'Sedan',
                'quilometragem' => 5000,
                'combustivel' => '45',
                'motor' => '1.6',
                'cambio' => 'Manual',
                'descricao' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets',
                'created_at' => '2025-11-11 02:31:16',
                'updated_at' => '2025-11-11 02:31:16',
            ],
            // Carro 8: 208
            [
                'id' => 8,
                'modelo' => '208',
                'marca' => 'Peugeot',
                'ano' => 2024,
                'cor' => 'azul',
                'preco' => 99000.00,
                'imagem_capa' => 'https://www.pca-services.fr/wp-content/uploads/2020/07/peugeot_24208allurehb2fb_angularfront.png',
                'imagem_url' => 'https://www.clarin.com/img/2024/10/10/wClZvd_za_1256x620__1.jpg',
                'imagem_url2' => 'https://www.pca-services.fr/wp-content/uploads/2020/07/peugeot_24208allurehb2fb_dashboard.png',
                'imagem_url3' => 'https://s2-autoesporte.glbimg.com/SbUbMS5wgXa6oJmRuWL00jHUQCg=/0x0:620x413/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2020/B/g/g0kMrpTNKo9MTWYok9RA/2020-08-25-dz8-14.jpg',
                'carroceria' => 'Hatch',
                'quilometragem' => 15000,
                'combustivel' => '50',
                'motor' => '1.0 Turbo',
                'cambio' => 'Manual',
                'descricao' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets',
                'created_at' => '2025-11-11 02:35:00',
                'updated_at' => '2025-11-11 02:35:00',
            ],
            // Carro 9: Virtus
            [
                'id' => 9,
                'modelo' => 'Virtus',
                'marca' => 'Volkswagen',
                'ano' => 2022,
                'cor' => 'cinza',
                'preco' => 95000.00,
                'imagem_capa' => 'https://www.grandebelem.com.br/assets/uploads/nt_veiculos/81342-Ve--culo--png-_-440x250.png?v=0.3',
                'imagem_url' => 'https://motorshow.com.br/wp-content/uploads/sites/2/2018/03/vw-virtus-douglas2.jpeg?x71212',
                'imagem_url2' => 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjHIbYBvGFoP9UHJfuPZGpZYnxGCgPargy9XiWPy50vZkuqCOiu-DFU6-7GN8hVzlSDudE_DQBMRdyQvHMT4Zyr5G0dJeM-lSLsGYnHJso45xXdGJaPOxnYUBClm4L69TB2OoHMpY2JyMiG/s640-rw/Virtus-GTS-Interior+%25282%2529.jpg',
                'imagem_url3' => 'https://motorshow.com.br/wp-content/uploads/sites/2/2018/02/10_ms414_volkswagen-virtus1.jpg?x71212',
                'carroceria' => 'Sedan',
                'quilometragem' => 25000,
                'combustivel' => '50',
                'motor' => '2.0',
                'cambio' => 'Automático',
                'descricao' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets',
                'created_at' => '2025-11-11 02:32:27',
                'updated_at' => '2025-11-11 02:32:27',
            ],
            // Carro 13: Corolla
            [
                'id' => 13,
                'modelo' => 'Corolla',
                'marca' => 'Toyota',
                'ano' => 2012,
                'cor' => 'Branco',
                'preco' => 50550.00,
                'imagem_capa' => 'https://estofariabrasil.com.br/wp-content/uploads/2020/04/Corolla-1.png',
                'imagem_url' => 'https://http2.mlstatic.com/D_NQ_NP_2X_776461-MLB94899066710_102025-T-toyota-corolla-xei-20-flex-16v-aut.webp',
                'imagem_url2' => 'https://quatrorodas.abril.com.br/wp-content/uploads/2016/10/626_sedas_03.jpeg?quality=70&strip=info&w=928&w=636',
                'imagem_url3' => 'https://quatrorodas.abril.com.br/wp-content/uploads/2016/10/626_sedas_07.jpeg?quality=70&strip=info&w=928&w=636',
                'carroceria' => 'Sedan',
                'quilometragem' => 150230,
                'combustivel' => '42',
                'motor' => '2.0',
                'cambio' => 'Automático',
                'descricao' => NULL,
                'created_at' => '2025-11-11 03:07:57',
                'updated_at' => '2025-11-11 03:07:57',
            ],
            // Carro 14: Civic
            [
                'id' => 14,
                'modelo' => 'Civic',
                'marca' => 'Honda',
                'ano' => 2019,
                'cor' => 'Preto',
                'preco' => 94430.00,
                'imagem_capa' => 'https://production.autoforce.com/uploads/version/profile_image/5451/comprar-sport_87c49018bc.png',
                'imagem_url' => 'https://www.webmotors.com.br/wp-content/uploads/2018/02/19182748/2-honda_civic_sport_10_copy.png',
                'imagem_url2' => 'https://quatrorodas.abril.com.br/wp-content/uploads/2016/11/580116da0e2163027007cf6apainel-honda-civic-sport-manual.jpeg?quality=70&strip=all&strip=all',
                'imagem_url3' => 'https://i0.statig.com.br/bancodeimagens/imgalta/6o/l6/zc/6ol6zc84065q2mw5vfcg7gtsi.jpg',
                'carroceria' => 'Sedan',
                'quilometragem' => 74220,
                'combustivel' => '50',
                'motor' => '2.0',
                'cambio' => 'Automático',
                'descricao' => NULL,
                'created_at' => '2025-11-11 03:10:41',
                'updated_at' => '2025-11-11 03:10:41',
            ],
            // Carro 15: Ka
            [
                'id' => 15,
                'modelo' => 'Ka',
                'marca' => 'Ford',
                'ano' => 2016,
                'cor' => 'Branco',
                'preco' => 42000.00,
                'imagem_capa' => 'https://i0.wp.com/www.highspeedbrazil.com.br/wp-content/uploads/2017/04/ford_ka.png?ssl=1',
                'imagem_url' => 'https://img.olx.com.br/images/73/733587917856031.webp',
                'imagem_url2' => 'https://image1.mobiauto.com.br/images/api/images/v1.0/79631965/transform/fl_progressive,f_webp,q_85,w_959',
                'imagem_url3' => 'https://carrosemduvida.com/wp-content/uploads/2017/04/ka-traseira.jpg',
                'carroceria' => 'Hatch',
                'quilometragem' => 65000,
                'combustivel' => '48',
                'motor' => '1.0',
                'cambio' => 'Manual',
                'descricao' => NULL,
                'created_at' => '2025-11-11 03:12:53',
                'updated_at' => '2025-11-11 03:12:53',
            ],
        ]);

        // 3. Reseta o auto-incremento para continuar após o último ID usado (15)
        DB::statement('ALTER TABLE carros AUTO_INCREMENT = 16;'); 
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}